export const balance: string;
export const chart: string;
export const cl1: string;
export const cl2: string;
export const cl3: string;
export const container: string;
export const data: string;
export const row: string;
export const table: string;
