export const buttons: string;
export const container: string;
export const difficon: string;
export const difftitle: string;
export const diffvalue: string;
export const links: string;
export const portficon: string;
export const portftitle: string;
export const value: string;
